# Generated by Django 4.1.2 on 2022-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Console",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("edition", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Played",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Last Played Date")),
                (
                    "time",
                    models.CharField(
                        choices=[("M", "Morning"), ("D", "Day"), ("N", "Night")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=25)),
                ("description", models.TextField(max_length=250)),
                ("age", models.IntegerField()),
                ("consoles", models.ManyToManyField(to="main_app.console")),
            ],
        ),
    ]
