# Generated by Django 4.1.2 on 2022-10-19 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Playing Date")),
                (
                    "time",
                    models.CharField(
                        choices=[("M", "Morning"), ("D", "Day"), ("N", "Night")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="Played",
        ),
        migrations.AlterField(
            model_name="videogame",
            name="genre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="videogame",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="playing",
            name="video_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.videogame"
            ),
        ),
    ]
