# Generated by Django 4.1.2 on 2022-10-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_playing_delete_played_alter_videogame_genre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playing",
            old_name="video_game",
            new_name="game",
        ),
    ]
